import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ClassificationService {
  classification = [
    {detailType : "Cash On Hand", category: "Current Asset", subCategory: "Cash"},
      {detailType : "Checking", category: "Current Asset", subCategory: "Cash"},
      {detailType : "Money Market", category: "Current Asset", subCategory: "Cash"},
      {detailType : "Rents Held In Trust", category: "Current Asset", subCategory: "Cash"},
      {detailType : "Savings", category: "Current Asset", subCategory: "Cash"},
      {detailType : "Accounts Receivable", category: "Current Asset", subCategory: "Accounts Receivable"},
      {detailType : "Allowance For Bad Debts", category: "Current Asset", subCategory: "Accounts Receivable"},
      {detailType : "Development Costs", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Employee Cash Advances", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Inventory", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Investments Mortgage Real Estate Loans", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Investments Tax-Exempt Securities", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Investments U.S. Government Obligations", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Investment_ Other", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Loans To Officers", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Loans To Others", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Loans To Stockholders", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Other Current Assets", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Prepaid Expenses", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Reitanage", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Undeposited Funds", category: "Current Asset", subCategory: "Other Current Assets"},
      {detailType : "Accumulated Amortization", category: "Non-Current Assets", subCategory: "Intangible Assets"},
      {detailType : "Accumulated Depletion", category: "Non-Current Assets", subCategory: "Intangible Assets"},
      {detailType : "Accumulated Depreciation", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Buildings", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Depletable Assets", category: "Non-Current Assets", subCategory: "Intangible Assets"},
      {detailType : "Fixed Asset Computers", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Fixed Asset Copiers", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Fixed Asset Furniture", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Fixed Asset Other Tools Equipment", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Fixed Asset Phone", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Fixed Asset Photo Video", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Fixed Asset Software", category: "Non-Current Assets", subCategory: "Intangible Assets"},
      {detailType : "Furniture And Fixtures", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Intangible Assets", category: "Non-Current Assets", subCategory: "Intangible Assets"},
      {detailType : "Land", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Leasehold Improvement", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Machinery And Equipment", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Other Fixed Assets", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Vehicles", category: "Non-Current Assets", subCategory: "Fixed Assets"},
      {detailType : "Accumulated Amortization Of Other Assets", category: "Non-Current Assets", subCategory: "Intangible Assets"},
      {detailType : "Goodwill", category: "Non-Current Assets", subCategory: "Intangible Assets"},
      {detailType : "Lease Buyout", category: "Non-Current Assets", subCategory: "Other Assets"},
      {detailType : "Licenses", category: "Non-Current Assets", subCategory: "Other Assets"},
      {detailType : "Organizational Costs", category: "Non-Current Assets", subCategory: "Other Assets"},
      {detailType : "Other Long Term Assets", category: "Non-Current Assets", subCategory: "Other Assets"},
      {detailType : "Security Deposits", category: "Non-Current Assets", subCategory: "Other Assets"},
      {detailType : "Accounts Payable", category: "Current Liabilities", subCategory: "Accounts Payable"},
      {detailType : "Credit Card", category: "Current Liabilities", subCategory: "Short Term Debt"},
      {detailType : "Federal Income Tax Payable", category: "Current Liabilities", subCategory: "Tax Liability"},
      {detailType : "Insurance Payable", category: "Current Liabilities", subCategory: "Accounts Payable"},
      {detailType : "Line Ff Credit", category: "Current Liabilities", subCategory: "Short Term Debt"},
      {detailType : "Loan Payable", category: "Current Liabilities", subCategory: "Short Term Debt"},
      {detailType : "Other Current Liabilities", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Payroll Tax Payable", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Prepaid Expenses Payable", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Rents In Trust Liability", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Sales Tax Payable", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Global Tax Payable", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "State Local Income Tax Payable", category: "Current Liabilities", subCategory: "Tax Liability"},
      {detailType : "Trust Accounts Liabilities", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Undistributed Tips", category: "Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Notes Payable", category: "Non-Current Liabilities", subCategory: "Long Term Liability"},
      {detailType : "Other Long Term Liabilities", category: "Non-Current Liabilities", subCategory: "Other Current Liabilities"},
      {detailType : "Shareholder Notes Payable", category: "Non-Current Liabilities", subCategory: "Long Term Liability"},
      {detailType : "Accumulated Adjustment", category: "Equity", subCategory: "Equity"},
      {detailType : "Common Stock", category: "Equity", subCategory: "Equity"},
      {detailType : "Estimated Taxes", category: "Equity", subCategory: "Equity"},
      {detailType : "Healthcare", category: "Equity", subCategory: "Equity"},
      {detailType : "Opening Balance Equity", category: "Equity", subCategory: "Equity"},
      {detailType : "Owner's Equity", category: "Equity", subCategory: "Equity"},
      {detailType : "Paid In Capital Or Surplus", category: "Equity", subCategory: "Equity"},
      {detailType : "Partner Contributions", category: "Equity", subCategory: "Equity"},
      {detailType : "Partners Distributions", category: "Equity", subCategory: "Retained Earnings"},
      {detailType : "Partner's Equity", category: "Equity", subCategory: "Equity"},
      {detailType : "Personal Expenses", category: "Equity", subCategory: "Equity"},
      {detailType : "Personal Income", category: "Equity", subCategory: "Equity"},
      {detailType : "Preferred Stock", category: "Equity", subCategory: "Equity"},
      {detailType : "Retained Earnings", category: "Equity", subCategory: "Retained Earnings"},
      {detailType : "Treasury Stock", category: "Equity", subCategory: "Equity"},
      {detailType : "Discounts Refunds Given", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Non Profit Income", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Other Primary Income", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Sales Of Product Income", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Service Fee Income", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Unapplied Cash Payment Income", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Dividend Income", category: "Revenue", subCategory: "Dividend Income"},
      {detailType : "Interest Earned", category: "Revenue", subCategory: "Interest Earnings"},
      {detailType : "Other Investment Income", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Other Miscellaneous Income", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Tax Exempt Interest", category: "Revenue", subCategory: "Revenue"},
      {detailType : "Cost Of Labor COS", category: "Cost of Sales", subCategory: "Fixed COS"},
      {detailType : "Equipment Rental COS", category: "Cost of Sales", subCategory: "Fixed COS"},
      {detailType : "Other Costs Of Service Cos", category: "Cost of Sales", subCategory: "Variable COS"},
      {detailType : "Shipping Freight Delivery Cos", category: "Cost of Sales", subCategory: "Variable COS"},
      {detailType : "Supplies Materials Cogs", category: "Cost of Sales", subCategory: "Variable COS"},
      {detailType : "Advertising Promotional", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Auto", category: "Expenses", subCategory: "Variable Expenses"},
      {detailType : "Bad Debts", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Charitable Contributions", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Cost Of Labor", category: "Expenses", subCategory: "Variable Expenses"},
      {detailType : "Dues Subscriptions", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Entertainment", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Entertainment Meals", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Equipment Rental", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Finance Costs", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Insurance", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Interest Paid", category: "Expenses", subCategory: "Interest Expenses"},
      {detailType : "Legal Professional Fees", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Office General Administrative Expenses", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Other Business Expenses", category: "Expenses", subCategory: "Variable Expenses"},
      {detailType : "Other Miscellaneous Service Cost", category: "Expenses", subCategory: "Expenses"},
      {detailType : "Payroll Expenses", category: "Expenses", subCategory: "Variable Expenses"},
      {detailType : "Promotional Meals", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Rent Or Lease Of Buildings", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Repair Maintenance", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Shipping, Freight Delivery", category: "Expenses", subCategory: "Variable Expenses"},
      {detailType : "Supplies Materials", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Taxes Paid", category: "Expenses", subCategory: "Taxes Paid"},
      {detailType : "Travel", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Travel Meals", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Unapplied Cash Bill Payment Expense", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Utilities", category: "Expenses", subCategory: "Fixed Expenses"},
      // {detailType : "Amortization", category: "Expenses", subCategory: "Depreciation & Amortization"},
      // {detailType : "Depreciation", category: "Expenses", subCategory: "Depreciation & Amortization"},
      {detailType : "Amortization", category: "Expenses", subCategory: "Expenses"},
      {detailType : "Depreciation", category: "Expenses", subCategory: "Expenses"},
      {detailType : "Exchange Gains Or Loss", category: "Expenses", subCategory: "Other Income/Loss"},
      {detailType : "Gas And Fuel", category: "Expenses", subCategory: "Variable Expenses"},
      {detailType : "Home Office", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Homeowner Rental Insurance", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Mortgage Interest Home Office ", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Other Home Office Expenses", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Other Miscellaneous Expense", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Other Vehicle Expense ", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Parking And Tolls", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Penalties Settlements", category: "Expenses", subCategory: "Expenses"},
      {detailType : "Rent And Lease Home Office", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Repairs And Maintenance Home Office", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Utilities Home Office", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Vehicle", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Vehicle Insurance", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Vehicle Lease", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Vehicle Loan", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Vehicle Loan Interest", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Vehicle Registration", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Vehicle Repairs", category: "Expenses", subCategory: "Variable Expenses"},
      {detailType : "Bank Charges", category: "Expenses", subCategory: "Fixed Expenses"},
      {detailType : "Wash And Road Services", category: "Expenses", subCategory: "Fixed Expenses"}
      ];
  constructor() { }
}
